src/Component/BlazorComponent/Components/Core/Base/BDomComponentBase.cs
src/Component/BlazorComponent/Components/Core/CssProcess/CssBuilder.cs
src/Component/BlazorComponent/Components/Core/Model/ThemeModel.cs
src/Component/BlazorComponent/Components/Core/Variables.cs
src/Component/BlazorComponent/Components/Grid/BCol.razor.cs

refactor: CssBuilder

---

src/Component/BlazorComponent/Components/SlotComponent.cs

Supports nested SlotComponents:
``` html
<SlotComponent>
<SlotComponent>
...
</SlotComponent>
</SlotComponent>
```

feat(core): 🆕 Support nested SlotComponents

---

src/Component/BlazorComponent/Components/Select/BSelect.razor
src/Component/BlazorComponent/Components/Select/BSelect.razor.cs

- refactor(select): ♻ Refactor the way to update text

refactor(select): Refactor the way to update text

---

src/Component/BlazorComponent/I18n/I18nServiceCollectionExtensions.cs

- i18n json files support comments and trailing commas [#74](https://github.com/BlazorComponent/BlazorComponent/pull/74)

perf(i18n): i18n json files support comments and trailing commas

---

src/Component/BlazorComponent/Components/Checkbox/BSimpleCheckbox.razor
src/Component/BlazorComponent/Components/Checkbox/BSimpleCheckbox.razor.cs

input event in Vue is the same as Blazor's ValueChanged.

refactor: Rename OnInput to ValueChanged

---

src/Component/BlazorComponent/Components/OtpInput/BOtpInput.razor.cs

resolve https://github.com/BlazorComponent/MASA.Blazor/issues/370

fix(OTP Input): finish event only trigger on input the last value

---

src/Component/BlazorComponent/Mixins/Linkable/Linker.cs

PR (c411ca9) did not solve the problem.

🐛 fix(linker): listItem with href '/' should not be active all the time

---

src/Component/BlazorComponent/BlazorComponent.csproj
src/Component/BlazorComponent/Components/Dialog/BDialog.razor.cs
src/Component/BlazorComponent/Components/Form/EditContextExtensions.cs
src/Component/BlazorComponent/Components/List/BListGroup.razor.cs
src/Component/BlazorComponent/Mixins/Menuable/BMenuable.cs

- remove warning [#11](https://github.com/BlazorComponent/BlazorComponent/pull/99)

chore: remove warning

---

src/Component/BlazorComponent/Web/ExTouchEventArgs.cs

make up ExTouchEventArgs class

fix(MSlider&MRangeSlider): make up ExTouchEventArgs class

---

src/Component/BlazorComponent/Components/PageTabs/Body/BPageTabsBody.razor

This is fix for [Pro issues 138](https://github.com/BlazorComponent/MASA.Blazor.Pro/issues/138)

fix(pagetabs):pagetabs dispose

---

src/Component/BlazorComponent/Components/Input/BInput.razor.cs

fix(BInput): remove DebounceMilliseconds property's parameter attribute

fix(BInput): remove DebounceMilliseconds property's parameter attribute

---

src/Component/BlazorComponent/Components/Input/BInput.razor.Validatable.cs

resolve https://github.com/BlazorComponent/MASA.Blazor/issues/437

fix(MSlider&MRangeSlider): resolve MSlider and MRangeSlider lag problem

---

src/Component/BlazorComponent/Components/Input/BInput.razor.Validatable.cs

resolve https://github.com/BlazorComponent/MASA.Blazor/issues/461

fix(MTextField): fix textfield reback

---

src/Component/BlazorComponent/I18n/I18n.cs
src/Component/BlazorComponent/I18n/I18nCache.cs
src/Component/BlazorComponent/I18n/I18nConfig.cs
src/Component/BlazorComponent/I18n/I18nReader.cs
src/Component/BlazorComponent/I18n/I18nServiceCollectionExtensions.cs
src/Component/BlazorComponent/I18n/JsRuntime/CookieStorage.cs
src/Component/BlazorComponent/_Imports.cs

- Support nested  [#131](https://github.com/BlazorComponent/BlazorComponent/pull/131)
- Fix startup error in wasm mode  [#131](https://github.com/BlazorComponent/BlazorComponent/pull/131)

feat(i18n):support nested

---

src/Component/BlazorComponent/Components/Input/BInput.razor.Validatable.cs

remove TempValue use InputValue

reactor: remove MTextField TempValue property

---

src/Component/BlazorComponent/I18n/I18n.cs
src/Component/BlazorComponent/I18n/I18nConfig.cs
src/Component/BlazorComponent/I18n/I18nReader.cs
src/Component/BlazorComponent/I18n/I18nServiceCollectionExtensions.cs

- Fixed the problem that an error will be reported when reading an encoded file other than utf8  [#136](https://github.com/BlazorComponent/BlazorComponent/pull/136)

fix(i18n):fixed the problem that an error will be reported when reading an encoded file other than utf8

---

src/Component/BlazorComponent/Extensions/DependencyInjection/BlazorComponentBuilder.cs
src/Component/BlazorComponent/Extensions/DependencyInjection/IBlazorComponentBuilder.cs
src/Component/BlazorComponent/Extensions/DependencyInjection/ServiceCollectionExtensions.cs
src/Component/BlazorComponent/I18n/EmbeddedLocales.cs
src/Component/BlazorComponent/I18n/I18n.cs
src/Component/BlazorComponent/I18n/I18nCache.cs
src/Component/BlazorComponent/I18n/I18nServiceCollectionExtensions.cs

Change the type of culture to CultureInfo instead of string, and add IBlazorComponentBuilder interface for better originizational injection.

feat: change the type of culture to CultureInfo instead of string

---

src/Component/BlazorComponent/Components/Treeview/BTreeview.razor.cs

watch the changes of keys to rebuild the tree, and add the public method `RebuildTree` to rebuild the tree for users.

refactor(Treeview): watch the changes of keys to rebuild the tree

---

src/Component/BlazorComponent/Components/Input/BInput.razor.cs

Temporary solution, the problem still exists and will be resolved at 0.6.

🐛 fix(TextField): add a flag to determine whether the user is entering

---

src/Component/BlazorComponent/Components/List/BListItem.razor

resolve https://github.com/BlazorComponent/MASA.Blazor/issues/589.

🐛 fix: BlazorComponent/MASA.Blazor#589

---

src/Component/BlazorComponent/Components/Cascader/CascaderList/BCascaderList.razor
src/Component/BlazorComponent/Components/Cascader/CascaderList/BCascaderList.razor.cs
src/Component/BlazorComponent/Components/Cascader/Menu/List/BCascaderList.razor
src/Component/BlazorComponent/Components/Cascader/Menu/List/BCascaderList.razor.cs

resolve BlazorComponent/MASA.Blazor#597

🐛 fix: clear the child cascader if select the selection

---

src/Component/BlazorComponent/Components/TextField/Content/Control/InputSlot/DefaultSlot/TextFieldSlot/Affix/BTextFieldAffix.razor

resolve BlazorCOmponent/MASA.Blazor#600

🐛 fix(TextField): Prefix overlaps with label

---

src/Component/BlazorComponent/Components/Cascader/CascaderList/BCascaderList.razor
src/Component/BlazorComponent/Components/Cascader/CascaderList/BCascaderList.razor.cs

resolve BlazorComponent/Masa.Blazor#615

🐛 fix(Cascader): only the sublist should be displayed after clicking the item

---

src/Component/BlazorComponent/Mixins/Groupable/BGroupable.cs

resolve https://github.com/BlazorComponent/MASA.Blazor/issues/760

🐛 FIX(Tab): active style doesn't work

---

src/Component/BlazorComponent/Components/DataTable/DataTableHeader.cs
src/Component/BlazorComponent/Components/DataTable/DataTableHeader/Desktop/BDataTableHeaderDesktop.razor
src/Component/BlazorComponent/Components/DataTable/SimpleTable/DataTableHeaderAlign.cs

resolve BlazorComponent/Masa.Blazor#712

♻ refactor(DataTable): The Align type of DataTable header changes to enum

---

src/Component/BlazorComponent/Components/ProgressCircular/BProgressCircular.razor.cs
src/Component/BlazorComponent/Components/ProgressCircular/Svg/Circle/BProgressCircularCircle.razor

resolve BlazorComponent/Masa.Blazor#801

🆕 feat(ProgressCircular): Support for background color

---

src/Component/BlazorComponent/BlazorComponent.csproj
src/Component/BlazorComponent/Components/Form/EditContext/ValidationEventSubscriptions.cs
src/Component/BlazorComponent/Extensions/DependencyInjection/ServiceCollectionExtensions.cs

FluentValidation support generic type

---

src/Component/BlazorComponent/Components/Form/EditContext/ValidationEventSubscriptions.cs

Feature(form):form fluentValidate support recursive nesting

---

src/Component/BlazorComponent/Components/Form/EditContext/ValidationEventSubscriptions.cs
src/Component/BlazorComponent/Extensions/DependencyInjection/ServiceCollectionExtensions.cs

⏪ chore: rollback the PR #255

---

src/Component/BlazorComponent/Abstracts/Components/BComponentBase.cs
src/Component/BlazorComponent/Components/Checkbox/BCheckboxCheckbox.razor
src/Component/BlazorComponent/Components/Checkbox/BCheckboxCheckbox.razor.cs
src/Component/BlazorComponent/Components/Checkbox/BCheckboxDefaultSlot.razor
src/Component/BlazorComponent/Components/Checkbox/BCheckboxDefaultSlot.razor.cs
src/Component/BlazorComponent/Components/Checkbox/ICheckbox.cs
src/Component/BlazorComponent/Components/Input/BInput.razor.Validatable.cs
src/Component/BlazorComponent/Components/Input/BInput.razor.cs
src/Component/BlazorComponent/Components/Input/IInputJsCallbacks.cs
src/Component/BlazorComponent/Components/Input/InputJsInterop.cs
src/Component/BlazorComponent/Components/Switch/BSwitchDefaultSlot.razor
src/Component/BlazorComponent/Components/Switch/BSwitchDefaultSlot.razor.cs
src/Component/BlazorComponent/Components/Switch/ISwitch.cs
src/Component/BlazorComponent/Components/Switch/Switch/BSwitchSwitch.razor
src/Component/BlazorComponent/Components/Switch/Switch/BSwitchSwitch.razor.cs
src/Component/BlazorComponent/Components/Switch/Switch/Input/BSelectableInput.razor
src/Component/BlazorComponent/Components/Switch/Switch/Input/BSelectableInput.razor.cs
src/Component/BlazorComponent/Components/Switch/Switch/Progress/BSwitchProgress.razor
src/Component/BlazorComponent/Components/Switch/Switch/Progress/BSwitchProgress.razor.cs
src/Component/BlazorComponent/Mixins/Selectable/ISelectable.cs

resolve BlazorComponent/Masa.Blazor#710

🆕 feat(Selectable): TrueValue and FalseValue supports

---

src/Component/BlazorComponent/Components/ExpansionPanels/BExpansionPanels.razor.cs
src/Component/BlazorComponent/Components/ItemGroup/BItemGroup.razor.cs
src/Component/BlazorComponent/Components/ItemGroup/ItemGroupBase.cs
src/Component/BlazorComponent/Components/Window/BWindow.razor.cs

resolve masastack/MASA.Docs#83

🐛 fix(Window): click events from custom prev and next content don't work

---

src/Component/BlazorComponent.Web/build-js.ps1
src/Component/BlazorComponent.Web/package.json
src/Component/BlazorComponent.Web/rollup.config.maps.ts
src/Component/BlazorComponent.Web/src/proxies/maps/baidumap/index.js
src/Component/BlazorComponent.Web/yarn.lock

Add baidumap js code and update build script to support [MBaiduMap](https://github.com/BlazorComponent/MASA.Blazor/pull/951) component.
To update baidumap js code, edit:
`/src/proxies/maps/baidumap/index.js`
To rebuild js, run: 
`.\build-js.ps1 maps`
BaiduMap Javascript code need to be loaded dynamically when MBaiduMap component first rendering, so most definitions are unknown during compiling. It's hard to write code in Typescript. I'll try to switch these code in TS later

feat: Add baidumap js code and update build script

---

src/Component/BlazorComponent/Components/App/BApp.razor
src/Component/BlazorComponent/Components/App/BApp.razor.cs

Associate the PR
https://github.com/BlazorComponent/MASA.Blazor/pull/952

feat: Support for dynamic theme modification

---

src/Component/BlazorComponent/Components/Menu/BMenu.razor

resolve BlazorComponent/Masa.Blazor#917

🐛 fix(Menu): the position of last menu in app bar was wrong

---

src/Component/BlazorComponent/Components/Treeview/BTreeview.razor.cs
src/Component/BlazorComponent/Components/Treeview/TreeviewNode/BTreeviewNode.razor.cs

resolve BlazorComponent/Masa.Blazor#939

🐛 fix(Treeview): bugs when using LoadChildren and Selectable together

---

src/Component/BlazorComponent/Components/SlideGroup/BSlideGroup.razor.cs
src/Component/BlazorComponent/Components/Tabs/BTabs.razor.cs
src/Component/BlazorComponent/Components/Tabs/ITabs.cs
src/Component/BlazorComponent/JSInterop/DomEventJsInterop.cs

resolve BlazorComponent/Masa.Blazor#775

🐛 fix(Tabs): slider got 0 in dialog at the first opened

---

src/Component/BlazorComponent/Components/SlideGroup/BSlideGroup.razor
src/Component/BlazorComponent/Components/SlideGroup/BSlideGroup.razor.cs
src/Component/BlazorComponent/_Imports.cs

resolves BlazorComponent/Masa.Blazor#604

🆕 feat(SlideGroup): add resize observer

---

src/Component/BlazorComponent/Components/ExpansionPanels/BExpansionPanels.razor.cs
src/Component/BlazorComponent/Components/ItemGroup/BItemGroup.razor.cs
src/Component/BlazorComponent/Components/ItemGroup/ItemGroupBase.cs
src/Component/BlazorComponent/Components/SlideGroup/BSlideGroup.razor.cs
src/Component/BlazorComponent/Components/SlideGroup/ISlideGroup.cs
src/Component/BlazorComponent/Components/Window/BWindow.razor.cs
src/Component/BlazorComponent/Mixins/Groupable/BGroupable.cs

resolves BlazorComponent/Masa.Blazor#1010

fix(ItemGroup): Use an InternalValue(s) that does not affect the Value(s) parameter

---

src/Component/BlazorComponent/I18n/JsRuntime/CookieStorage.cs

feat:add domain parameter to CookieStorage.SetItemAsync method

---

src/Component/BlazorComponent/I18n/JsRuntime/CookieStorage.cs

feat: set the first-level domain when setting the cookie

---

src/Component/BlazorComponent/Components/Chip/Content/Close/BChipClose.razor

resolves BlazorComponent/Masa.Blazor#1076

🐛 fix(Chip): missing preventDefault and stopPropagation

---

src/Component/BlazorComponent/I18n/I18nReader.cs
src/Component/BlazorComponent/I18n/I18nServiceCollectionExtensions.cs

修正多语言文件编码与单文件发布
fixes BlazorComponent/Masa.Blazor#1074

fix(i18n): 修正多语言文件编码与单文件发布

---

src/Component/BlazorComponent/Components/ItemGroup/BRoutableGroupItem.razor.cs

issue: https://github.com/masastack/MASA.MC/issues/350

🐛 fix(ListItem): matched ListItem is sometimes not activated

---

src/Component/BlazorComponent/Components/List/BListGroup.razor.cs

issue: https://github.com/masastack/MASA.MC/issues/350

🐛 fix(ListGroup): routable list-group cannot expand after refresh

---

src/Component/BlazorComponent/Components/AppBar/BAppBarNavIcon.razor
src/Component/BlazorComponent/Components/AppBar/BAppBarNavIcon.razor.cs

resolves masastack/MASA.Blazor#1175

🐛 fix(AppBarNavIcon): custom Icon component doesn't work

---

src/Component/BlazorComponent/Components/App/BApp.razor.cs

because the `Dark` parameter is conflict with the `MasaBlazor.Theme.Dark`

♻ refactor(App): delete the Dark theme feature

---

src/Component/BlazorComponent/Components/Cascader/CascaderColumn/BCascaderColumn.razor.cs
src/Component/BlazorComponent/Mixins/Delayable/BDelayable.cs

Related issue: https://github.com/masastack/MASA.Auth/issues/879
CC @binwan-dev

fix(Cascader): Selection wasn't updated synchronously after value updated

---

src/Component/BlazorComponent/Components/Icon/BIcon.razor
src/Component/BlazorComponent/Components/Input/Content/AppendSlot/BInputAppendSlot.razor.cs
src/Component/BlazorComponent/Components/Input/Content/AppendSlot/Icon/BInputIcon.razor
src/Component/BlazorComponent/Components/Input/Content/AppendSlot/Icon/BInputIcon.razor.cs
src/Component/BlazorComponent/Components/Input/Content/PrependSlot/BInputPrependSlot.razor.cs
src/Component/BlazorComponent/Components/TextField/Content/AppendSlot/BTextFieldAppendSlot.razor.cs
src/Component/BlazorComponent/Components/TextField/Content/Control/InputSlot/PrependInnerSlot/BTextFieldPrependInnerSlot.razor.cs
src/Component/BlazorComponent/Components/TextField/ITextField.cs

resolves masastack/MASA.Blazor#1204

🐛 fix(Select): Clicking on the menu-down icon does not activate

---

src/Component/BlazorComponent.Web/src/proxies/echarts/index.ts

fix(ECharts): Special Character Conversion

---

src/Component/BlazorComponent/Mixins/Menuable/BMenuable.cs

fix:BMenuable Calc ComputedTop

---

src/Component/BlazorComponent/Components/DataTable/DataTableRowMouseEventArgs.cs
src/Component/BlazorComponent/Components/DataTable/DefaultSlot/Body/Items/Rows/DefaultRows/DefaultSimpleRow/BDataTableDefaultSimpleRow.razor
src/Component/BlazorComponent/Components/DataTable/DefaultSlot/Body/Items/Rows/DefaultRows/DefaultSimpleRow/BDataTableDefaultSimpleRow.razor.cs
src/Component/BlazorComponent/Components/DataTable/IDataTable.cs

resolves masastack/Masa.Blazor#1236

🆕 feat(DataTable): click, dbclick and contextmenu supports on Row

---

src/Component/BlazorComponent/Components/Hover/BHover.razor.cs
src/Component/BlazorComponent/Mixins/Activatable/BActivatableBase.cs

resolves masastack/Masa.Blazor#1223

🐛 fix(Hover): wrong style cursor:point

---

src/Component/BlazorComponent/Components/Dialog/BDialog.razor.cs
src/Component/BlazorComponent/Components/Menu/BMenu.razor.cs
src/Component/BlazorComponent/Mixins/OutsideClick/OutsideClickJSModule.cs

related issue: https://github.com/masastack/MASA.TSC/issues/357

fix(Dialog): Clicking the menu of autocomplete sometimes closes the dialog

---

src/Component/BlazorComponent/Abstracts/Components/NextTickComponentBase.cs
src/Component/BlazorComponent/Components/Dialog/BDialog.razor.cs
src/Component/BlazorComponent/Components/Input/BInput.razor.Validatable.cs
src/Component/BlazorComponent/Components/Menu/BMenu.razor.cs
src/Component/BlazorComponent/Components/NavigationDrawer/BNavigationDrawer.razor.cs

related issue: https://github.com/masastack/MASA.TSC/issues/357, https://github.com/masastack/MASA.Stack.Components/issues/582

fix(Dialog): UpdateDependentElements until OutsideClickJSModule was initialized

---

src/Component/BlazorComponent/Components/InfiniteScroll/BInfiniteScroll.razor.cs

resolves masastack/Masa.Blazor#1301

🐛 fix(InfiniteScroll): parent ref from MainLayout doesn't work

---

src/Component/BlazorComponent/Components/DataTable/DataTableHeader/BDataTableHeader.razor
src/Component/BlazorComponent/Components/DataTable/DataTableHeader/BDataTableHeader.razor.cs
src/Component/BlazorComponent/Components/DataTable/DataTableHeader/Desktop/BDataTableHeaderDesktop.razor
src/Component/BlazorComponent/Components/DataTable/DataTableHeader/Desktop/BDataTableHeaderDesktop.razor.cs
src/Component/BlazorComponent/Components/DataTable/DataTableHeader/Desktop/GroupByToggle/BDataTableGroupByToggle.razor
src/Component/BlazorComponent/Components/DataTable/DataTableHeader/Desktop/GroupByToggle/BDataTableGroupByToggle.razor.cs
src/Component/BlazorComponent/Components/DataTable/DefaultSlot/Body/Items/GroupedRows/DefaultGroupedRow/BDataTableDefaultGroupedRow.razor
src/Component/BlazorComponent/Components/DataTable/DefaultSlot/Body/Items/GroupedRows/DefaultGroupedRow/BDataTableDefaultGroupedRow.razor.cs
src/Component/BlazorComponent/Components/DataTable/IDataTable.cs
src/Component/BlazorComponent/I18n/Locales/en-US.json
src/Component/BlazorComponent/I18n/Locales/zh-CN.json
src/Component/BlazorComponent/I18n/Locales/zh-TW.json

resolves masastack/MASA.Blazor#1309

🐛 fix(DataTable): group text and column name no correct when grouping

---

src/Component/BlazorComponent/Abstracts/Components/BComponentBase.cs
src/Component/BlazorComponent/Components/SlideGroup/BSlideGroup.razor.cs

related issue: https://github.com/masastack/MASA.DCC/issues/549

🐛 fix(SlideGroup): arrows shaking

---

src/Component/BlazorComponent/Components/Input/BInput.razor.Validatable.cs

resolves masastack/MASA.Blazor#1351

🆕 feat(Input): add the BlurAsync public method

---

src/Component/BlazorComponent.Web/package.json
src/Component/BlazorComponent.Web/src/proxies/markdown-it/index.ts

resolves masastack/MASA.Blazor#1354

🆕 feat(MarkdownIt): support for task list

---

src/Component/BlazorComponent/Components/Input/BInput.razor.Validatable.cs

resolves masastack/Masa.Blazor#1427

🐛 fix(Select): Select item cannot change the value at the first time

---

src/Component/BlazorComponent/Abstracts/Components/BComponentBase.cs

resolves masastack/MASA.Blazor#1450

🐛 fix(Defaults): form validation doesn't work when defaults provided

---

src/Component/BlazorComponent.Web/src/proxies/echarts/index.ts

resolves masastack/Masa.Blazor#1500

🐛 fix(ECharts): use resizeobserver api to watch size changing

---

src/Component/BlazorComponent/Components/Transition/Elements/TransitionElementBase.cs
src/Component/BlazorComponent/Components/Transition/TransitionJsInvoker.cs

resolves masastack/Masa.Blazor#1199

🐛 fix(Transition): transition may not finish when the delay was high

---

src/Component/BlazorComponent/Components/Pagination/IPagination.cs
src/Component/BlazorComponent/Components/Pagination/List/Items/BPaginationItems.razor
src/Component/BlazorComponent/Components/Pagination/List/Items/BPaginationItems.razor.cs

resolves masastack/MASA.Blazor#1640
```razor
<MPagination @bind-Value="_page" Length="3" HrefFormat="/list?page={0}"></MPagination>
```
will generate some code that looks like:
```html
...
<a class="m-pagination__item" href="/list?page=1">1</a>
<a class="m-pagination__item" href="/list?page=2">2</a>
<a class="m-pagination__item" href="/list?page=3">3</a>
...
```

🆕 feat(Pagination): add `HrefFormat` parameter for SEO

---

src/Component/BlazorComponent/Abstracts/Components/BComponentBase.cs
src/Component/BlazorComponent/Components/Treeview/BTreeview.razor.cs

resolves masastack/Masa.Blazor#1599

🆕 feat(Treeview): open parent nodes of filtered node after filtering

---

src/Component/BlazorComponent/Abstracts/Builder/ThemeCssBuilder.cs
src/Component/BlazorComponent/Services/ThemeOptions.cs

add `OnPrimary`, `OnSecondary`, `OnAccent`, `OnError`, `Surface` and `OnSurface` color roles

🆕 feat(Theme): support for more color roles

---

src/Component/BlazorComponent/Components/Treeview/BTreeview.razor
src/Component/BlazorComponent/Components/Treeview/BTreeview.razor.cs
src/Component/BlazorComponent/Components/Treeview/ITreeview.cs
src/Component/BlazorComponent/Components/Treeview/NodeState.cs
src/Component/BlazorComponent/Components/Treeview/TreeviewNode/BTreeviewNode.razor.cs

Dear @wildwind2000,
Thank you for your contribution and the time you have invested in submitting the Pull Request (#555) to our project. We appreciate your efforts and the interest you have shown in contributing to our community.
After careful consideration and review, we have made the decision to retract your PR. We would like to explain the reasons behind this decision and provide feedback to assist you in your future contributions.
Reason for retraction:
The changes made to the refactored treeview were too extensive, and there were not enough test cases and identified issues. As a result, the commit for this change has been reverted.
We encourage you to continue participating in our project. Although this particular PR has been retracted, we invite you to submit other contributions in …

⏪ chore: revert commit 347d217

---

src/Component/BlazorComponent/Components/Treeview/BTreeview.razor.cs

fixes masastack/Masa.Blazor#1799

🐛 fix(Treeview): conflict between OnInput and ValueChanged

---

src/Component/BlazorComponent.Web/src/proxies/echarts/index.ts

add echarts showLoading, hideLoading js proxy method

add echarts js proxy method
